//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVIMLI_KITAPCILIKAPI.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satılan_Kitaplar
    {
        public int İD { get; set; }
        public string ESERİN_ADİ { get; set; }
        public string ESERİN_YAZARI { get; set; }
        public string KONUMU { get; set; }
        public double FİYATİ { get; set; }
        public int ADEDİ { get; set; }
    }
}
